### ISSUE TITLE
Can't find injected web3 using ./utils/getWeb3.js

### ISSUE THREAD

**Issue by andytudhope** [truffle-box/truffle-box-react#5]
The latest commit that changes how the web3 object is handled seems to break things for me. It does not see the injected web3 object and defaults to the local one every time, no matter which network I connect MetaMask to.

OS: Mac 10.12.5
Browser: Chrome 

I'm a newb to React, so forgive me, but my sense was that there was something amiss with the lifecycle hooks and waiting for the `load` event. I tried changing the code in `app.js` to make a button that would only call `getWeb3` when clicked, but that failed even more, so the issue is definitely with the getWeb3.js file. I'm just not sure how to edit it to get it to pick up the injected web3 at the right time...

<img width="386" alt="screen shot 2017-06-27 at 10 42 55 am" src="https://user-images.githubusercontent.com/13001517/27579446-d842a5ce-5b27-11e7-9010-5e02f970fb89.png">

**Comment by andytudhope** [comment]
fixed by adding let web3 = window.web3 in getWeb3.js

**Comment by scorpion9979** [comment]
web3 = window.web3 does not always provide a consistent API. I've had several issues with this on mobile dApp browsers. The solution is to use `new Web3( Web3.givenProvider)` instead.

**Comment by scorpion9979** [comment]
#99
